### PR TITLE
bt-315: [BUG] Add notifications element to Auth pages

### LINKED ISSUE #315: [BUG] Error notification for email taken not showing up on sign-up page
**Description:**
When a user tries to sign up with an email already in use, a toast error notification should appear informing user.

**Steps to reproduce:**

1. Go to Sign Up page.
2. Try to sign up with a use email.

**Actual Result:**
Error occurs but no notification is show by toast.

**Expected Result:**
A toast notification indicating that the email is already taken.

**Visual Proof (screenshots, videos, text):**
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/471905b9-3553-4346-8b7b-4ddddbb6f6f9

**Severity:**
Major (S3)

### PR DESCRIPTION
**Pull request by JosuerBague**
Close #315 

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/c72b5dc6-cb59-43fa-94c5-3fd959bb3361

### CODE REVIEW

**Review by savinaDaria — APPROVED** [review]
works properly now

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]
we have Notifications in the root. we do not need to put it here

**Comment by JosuerBague** [comment]
> we have Notifications in the root. we do not need to put it here

Right now,
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/development/frontend/src/index.tsx

Auth routes are not children of the App, Perhaps this is a mistake on my part.

Should I change App then to not include PageLayout element for auth routes:
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/development/frontend/src/app/app.tsx

**Comment by JosuerBague** [comment]
Bug described here is caused by incorrect layouting. This will be fixed in a separate bug ticket.

**Pull request closed without merging**
