### PR TITLE
bt-701: Create employer profile layout

### LINKED ISSUE #701: Create component for Employer in admin user verification
We need to display all information from the employer onboarding page in the employer tab

Image

### PR DESCRIPTION
**Pull request by Simpsonkk**
image

### CODE REVIEW

**Review by vladjsp — APPROVED** [review]
The design looks good. Some mocked data will replace in my task connection employer deny/approval to API

**Comment by nikita-remeslov** [comment]
I think we should use this design
image
left side info
right side logo

**Comment by Simpsonkk** [comment]
image

**Comment by nikita-remeslov** [comment]
Looks like your tabs little bit different from talents page

**Comment by Simpsonkk** [comment]
image
image

**Comment by Simpsonkk** [comment]
image
image

tabs height was increased

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
