### PR TITLE
bt-802: update lms data endpoint

### LINKED ISSUE #336: Create endpoint to load userData from LMS
Our system pull data from LMS about students, badges, hard skills
You need to implement endpoint for this. We call this endpoint while we use onboarding process to store some data and set some data to onboarding fields.
~~prevent to sign up if email of new user is missing on LMS server~~ will be in task #691

### LINKED ISSUE #802: Update lms data endpoint
Add missed data

### PR DESCRIPTION
**Pull request by JemiJe**
fixed #336 
table was changed: `migrate:dev`. and build:shared, npm i, etc.
response will be exactly as on LMS
response example https://gist.github.com/JemiJe/8ca6efe5c8e8bc32681d3620562f32f8
please, test and find any problems as soon as possible. look carefully for response format, everything is ok?
for me all works as expected
```typescript
type LMSDataServerResponseDto = {
    talent: Talent;
    averageProjectScore: number | null;
    averageLectureScore: number | null;
    lectureDetails: LectureDetail[];
    projectCoachesFeedback: ProjectCoachesFeedback[];
    hrFeedback: HrFeedback;
    project: Project;
};
```

### CODE REVIEW

**Comment by MaksymGavatuk** [comment]
Why we need to do rollback ?

**Comment by MaksymGavatuk** [comment]
Don't change existing migration !!!
If you need to make changes in db create new migration and change fields or data moving etc...

**Comment by MaksymGavatuk** [comment]
If you push migration to develop you must not change it at all

**Comment by JemiJe** [comment]
> If you push migration to develop you must not change it at all

fixed, new migration created for this

**Review by MaksymGavatuk — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
