### PR TITLE
bt-355:  Use-our-logo-for-loader

### LINKED ISSUE #355: Use our logo for Loader
**Acceptance criteria:**
- When the user accesses the website, the BSA talent logo as a loader should be displayed to indicate that the website is in the process of loading.
- When the loader is active, the BSA talent logo must be clearly visible to the user.
- The logo loader should remain visible for the entire duration of the loader's operation. It should not disappear.
- The logo loader should be positioned in the middle of the page
- The logo loader must have sufficient contrast with the loader's background to ensure it is clearly distinguishable, readable, and matches with design

### PR DESCRIPTION
**Pull request by Simpsonkk**
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/92392661/7214e850-f7c1-4382-92fe-28c910b62c2d

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/92392661/160fd460-29fe-43a2-b72c-5602eca58f35

### CODE REVIEW

**Comment by ptarho** [comment]
Is it okay, that package-lock.json has 14k lines of changes?
The task code looks solid, but this aspect disappointed me

**Comment by vladjsp** [comment]
With disabled cache and 'regular 4G/LTE' network settings in FF our sign-in page loads in average time 25 sec. And all the time I see only a white screen and for a few milliseconds the logo loader, which changes content almost instantly. Same for reloading any page inside app. I'm not sure is this because of development mode or not. But the question is if there are any tricks to preload the logo loader and start showing it as soon as possible.

**Comment by Simpsonkk** [comment]
> Is it okay, that package-lock.json has 14k lines of changes? The task code looks solid, but this aspect disappointed me

I`ve already removed it, don't get upset so quickly )

**Comment by Simpsonkk** [comment]
> With disabled cache and 'regular 4G/LTE' network settings in FF our sign-in page loads in average time 25 sec. And all the time I see only a white screen and for a few milliseconds the logo loader, which changes content almost instantly. Same for reloading any page inside app. I'm not sure is this because of development mode or not. But the question is if there are any tricks to preload the logo loader and start showing it as soon as possible. 

For this task I just replaced prev loader with a new and wrote animation. I have the same about what you described also don`t know the reason.

**Review by ptarho — APPROVED** [review]

**Review by vladjsp — APPROVED** [review]
Works on the search candidates page while the request for profiles is pending and on other pages while loading.

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
